language: node_js

jobs:
  include:
    - stage: core
      if: branch = master AND type != pull_request
      script:
        - echo "CORE HERE"

    - stage: training
      language: java
      jdk: openjdk-8
      if: type = pull_request
      script:
        - TRAINING=$TRAVIS_PULL_REQUEST_BRANCH
        - echo $TRAVIS_PULL_REQUEST_BRANCH
        - echo $TRAINING
        - cd training/$TRAINING && node evaluate-training
