language: node_js

sudo: required

services:
  - docker

jobs:
  include:
    - stage: core
      if: branch = master
      script:
        - echo "CORE HERE"

    - stage: training
      if: type = pull_request
      script:
        - TRAINING=$TRAVIS_PULL_REQUEST_BRANCH
        - echo $TRAVIS_PULL_REQUEST_BRANCH
        - echo $TRAINING
        - node training/$TRAINING/index.js
